---
# file: site.yml
 - import_playbook: backupservers.yml
 - import_playbook: dbservers.yml
 - import_playbook: ovmmanagerservers.yml
 - import_playbook: ovmservers.yml
 - import_playbook: webtierservers.yml
 - import_playbook: wlsservers.yml
